version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.7
      - test-3.6
      - test-2.7

jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}

      - run:
          name: install dependencies
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
        
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mamba -f documentation  --enable-coverage

      - run:
          name: coverage
          command: |
            . venv/bin/activate
            coverage report   --include=*lleida_net*
            coverage html   --include=*lleida_net*

      - store_artifacts:
          path: test-reports
          destination: test-reports

  test-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7

  test-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7